export type Offer={id:string;store:string;classification:"Mejor compra verificada"|"Importación"|"Posible oferta"|"Precio sospechosamente bajo";price:number;shipping:number;taxes:number;total:number;delivery:string;warranty:string;updated:string;kind:string;confirmation:string;score:number;estimated:boolean};
export const demoProduct={name:"iPhone 17 Pro Max",brand:"Apple",storage:"256 GB",color:"Negro titanio",condition:"Nuevo"};
export const demoOffers:Offer[]=[
{id:"ml",store:"Mercado Libre",classification:"Mejor compra verificada",price:5889900,shipping:0,taxes:0,total:5889900,delivery:"Llega hoy a Bogotá",warranty:"Garantía local 12 meses",updated:"hace 12 min",kind:"Marketplace",confirmation:"Precio e inventario demo confirmables",score:92,estimated:false},
{id:"ishop",store:"iShop",classification:"Mejor compra verificada",price:6099900,shipping:0,taxes:0,total:6099900,delivery:"1–2 días",warranty:"Garantía oficial Apple",updated:"hace 34 min",kind:"Tienda verificada",confirmation:"Precio e inventario demo confirmables",score:97,estimated:false},
{id:"amazon",store:"Amazon",classification:"Importación",price:4820000,shipping:189000,taxes:934000,total:5943000,delivery:"8–14 días estimados",warranty:"Garantía internacional",updated:"hace 1 h",kind:"Importación",confirmation:"Conversión e impuestos estimados",score:78,estimated:true},
{id:"social",store:"Oferta por enlace",classification:"Posible oferta",price:5500000,shipping:20000,taxes:0,total:5520000,delivery:"Sin confirmar",warranty:"Sin confirmar",updated:"aportada hoy",kind:"Aportado por usuario",confirmation:"Datos incompletos",score:43,estimated:true},
{id:"unknown",store:"Vendedor independiente",classification:"Precio sospechosamente bajo",price:4390000,shipping:0,taxes:0,total:4390000,delivery:"Sin confirmar",warranty:"Sin confirmar",updated:"hace 3 h",kind:"Independiente",confirmation:"Requiere revisión antes de comprar",score:26,estimated:true}];
export const formatCop=(value:number)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(value);
